name: autoliftout
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - click
  - ipython
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pyyaml
  - scipy
  - scikit-image
  - petname
  - pandas
  - ipykernel
  - pytorch
  - torchvision
  - cudatoolkit=11.6
  - segmentation-models-pytorch
  - pyqt
