# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1396, 605)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Frame_Main = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame_Main.sizePolicy().hasHeightForWidth())
        self.Frame_Main.setSizePolicy(sizePolicy)
        self.Frame_Main.setMinimumSize(QtCore.QSize(0, 0))
        self.Frame_Main.setMaximumSize(QtCore.QSize(1800, 850))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Frame_Main.setFont(font)
        self.Frame_Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Main.setObjectName("Frame_Main")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Frame_Main)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_Images = QtWidgets.QFrame(self.Frame_Main)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_Images.setFont(font)
        self.frame_Images.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Images.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Images.setObjectName("frame_Images")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_Images)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_SEM = QtWidgets.QFrame(self.frame_Images)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_SEM.sizePolicy().hasHeightForWidth())
        self.frame_SEM.setSizePolicy(sizePolicy)
        self.frame_SEM.setMinimumSize(QtCore.QSize(675, 450))
        self.frame_SEM.setMaximumSize(QtCore.QSize(675, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_SEM.setFont(font)
        self.frame_SEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SEM.setLineWidth(0)
        self.frame_SEM.setObjectName("frame_SEM")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_SEM)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_SEM = QtWidgets.QLabel(self.frame_SEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SEM.sizePolicy().hasHeightForWidth())
        self.label_SEM.setSizePolicy(sizePolicy)
        self.label_SEM.setMinimumSize(QtCore.QSize(675, 450))
        self.label_SEM.setMaximumSize(QtCore.QSize(675, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SEM.setFont(font)
        self.label_SEM.setText("")
        self.label_SEM.setObjectName("label_SEM")
        self.gridLayout.addWidget(self.label_SEM, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_SEM, 0, 0, 1, 1)
        self.frame_FIB = QtWidgets.QFrame(self.frame_Images)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_FIB.sizePolicy().hasHeightForWidth())
        self.frame_FIB.setSizePolicy(sizePolicy)
        self.frame_FIB.setMinimumSize(QtCore.QSize(675, 450))
        self.frame_FIB.setMaximumSize(QtCore.QSize(675, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_FIB.setFont(font)
        self.frame_FIB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_FIB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_FIB.setObjectName("frame_FIB")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_FIB)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_FIB = QtWidgets.QLabel(self.frame_FIB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FIB.sizePolicy().hasHeightForWidth())
        self.label_FIB.setSizePolicy(sizePolicy)
        self.label_FIB.setMinimumSize(QtCore.QSize(675, 450))
        self.label_FIB.setMaximumSize(QtCore.QSize(675, 450))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_FIB.setFont(font)
        self.label_FIB.setText("")
        self.label_FIB.setObjectName("label_FIB")
        self.gridLayout_2.addWidget(self.label_FIB, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_FIB, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_Images)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_autoliftout = QtWidgets.QPushButton(self.frame)
        self.pushButton_autoliftout.setObjectName("pushButton_autoliftout")
        self.gridLayout_8.addWidget(self.pushButton_autoliftout, 0, 3, 1, 1)
        self.pushButton_load_sample_data = QtWidgets.QPushButton(self.frame)
        self.pushButton_load_sample_data.setObjectName("pushButton_load_sample_data")
        self.gridLayout_8.addWidget(self.pushButton_load_sample_data, 0, 1, 1, 1)
        self.pushButton_initialise = QtWidgets.QPushButton(self.frame)
        self.pushButton_initialise.setObjectName("pushButton_initialise")
        self.gridLayout_8.addWidget(self.pushButton_initialise, 0, 2, 1, 1)
        self.pushButton_test_popup = QtWidgets.QPushButton(self.frame)
        self.pushButton_test_popup.setObjectName("pushButton_test_popup")
        self.gridLayout_8.addWidget(self.pushButton_test_popup, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_status_1 = QtWidgets.QLabel(self.frame_2)
        self.label_status_1.setMinimumSize(QtCore.QSize(150, 0))
        self.label_status_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_status_1.setObjectName("label_status_1")
        self.gridLayout_5.addWidget(self.label_status_1, 1, 0, 1, 1)
        self.label_status_3 = QtWidgets.QLabel(self.frame_2)
        self.label_status_3.setMinimumSize(QtCore.QSize(577, 0))
        self.label_status_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_status_3.setText("")
        self.label_status_3.setObjectName("label_status_3")
        self.gridLayout_5.addWidget(self.label_status_3, 1, 3, 1, 1)
        self.label_status_2 = QtWidgets.QLabel(self.frame_2)
        self.label_status_2.setMinimumSize(QtCore.QSize(577, 0))
        self.label_status_2.setMaximumSize(QtCore.QSize(12345354, 16777215))
        self.label_status_2.setText("")
        self.label_status_2.setObjectName("label_status_2")
        self.gridLayout_5.addWidget(self.label_status_2, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_2, 1, 0, 1, 4)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame_Images, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.Frame_Main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1396, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_autoliftout.setText(_translate("MainWindow", "Run autoliftout"))
        self.pushButton_load_sample_data.setText(_translate("MainWindow", "Load Sample Data"))
        self.pushButton_initialise.setText(_translate("MainWindow", "Initialise"))
        self.pushButton_test_popup.setText(_translate("MainWindow", "Test_Popup"))
        self.label_status_1.setText(_translate("MainWindow", "Status:"))

