# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milling.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(10, 20, 978, 621))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_image = QtWidgets.QFrame(self.frame_main)
        self.frame_image.setMaximumSize(QtCore.QSize(1536, 1024))
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_image = QtWidgets.QLabel(self.frame_image)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.gridLayout_3.addWidget(self.label_image, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_image, 1, 1, 2, 1)
        self.frame_parameters = QtWidgets.QFrame(self.frame_main)
        self.frame_parameters.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_parameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_parameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_parameters.setObjectName("frame_parameters")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_parameters)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_05 = QtWidgets.QLabel(self.frame_parameters)
        self.label_05.setObjectName("label_05")
        self.gridLayout_4.addWidget(self.label_05, 8, 0, 1, 1)
        self.pushButton_runMilling = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_runMilling.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_runMilling.setObjectName("pushButton_runMilling")
        self.gridLayout_4.addWidget(self.pushButton_runMilling, 21, 0, 1, 2)
        self.doubleSpinBox_07 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_07.setObjectName("doubleSpinBox_07")
        self.gridLayout_4.addWidget(self.doubleSpinBox_07, 12, 1, 1, 1)
        self.label_07 = QtWidgets.QLabel(self.frame_parameters)
        self.label_07.setObjectName("label_07")
        self.gridLayout_4.addWidget(self.label_07, 12, 0, 1, 1)
        self.doubleSpinBox_03 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_03.setObjectName("doubleSpinBox_03")
        self.gridLayout_4.addWidget(self.doubleSpinBox_03, 4, 1, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.frame_parameters)
        self.label_02.setObjectName("label_02")
        self.gridLayout_4.addWidget(self.label_02, 3, 0, 1, 1)
        self.label_06 = QtWidgets.QLabel(self.frame_parameters)
        self.label_06.setObjectName("label_06")
        self.gridLayout_4.addWidget(self.label_06, 10, 0, 1, 1)
        self.doubleSpinBox_04 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_04.setObjectName("doubleSpinBox_04")
        self.gridLayout_4.addWidget(self.doubleSpinBox_04, 6, 1, 1, 1)
        self.label_08 = QtWidgets.QLabel(self.frame_parameters)
        self.label_08.setObjectName("label_08")
        self.gridLayout_4.addWidget(self.label_08, 14, 0, 1, 1)
        self.doubleSpinBox_02 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_02.setObjectName("doubleSpinBox_02")
        self.gridLayout_4.addWidget(self.doubleSpinBox_02, 3, 1, 1, 1)
        self.doubleSpinBox_01 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_01.setObjectName("doubleSpinBox_01")
        self.gridLayout_4.addWidget(self.doubleSpinBox_01, 2, 1, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.frame_parameters)
        self.label_03.setObjectName("label_03")
        self.gridLayout_4.addWidget(self.label_03, 4, 0, 1, 1)
        self.doubleSpinBox_06 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_06.setObjectName("doubleSpinBox_06")
        self.gridLayout_4.addWidget(self.doubleSpinBox_06, 10, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 20, 0, 1, 2)
        self.doubleSpinBox_08 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_08.setObjectName("doubleSpinBox_08")
        self.gridLayout_4.addWidget(self.doubleSpinBox_08, 14, 1, 1, 1)
        self.label_01 = QtWidgets.QLabel(self.frame_parameters)
        self.label_01.setObjectName("label_01")
        self.gridLayout_4.addWidget(self.label_01, 2, 0, 1, 1)
        self.label_04 = QtWidgets.QLabel(self.frame_parameters)
        self.label_04.setObjectName("label_04")
        self.gridLayout_4.addWidget(self.label_04, 6, 0, 1, 1)
        self.label_header = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.gridLayout_4.addWidget(self.label_header, 1, 0, 1, 2)
        self.doubleSpinBox_05 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_05.setObjectName("doubleSpinBox_05")
        self.gridLayout_4.addWidget(self.doubleSpinBox_05, 8, 1, 1, 1)
        self.doubleSpinBox_09 = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_09.setObjectName("doubleSpinBox_09")
        self.gridLayout_4.addWidget(self.doubleSpinBox_09, 15, 1, 1, 1)
        self.label_09 = QtWidgets.QLabel(self.frame_parameters)
        self.label_09.setObjectName("label_09")
        self.gridLayout_4.addWidget(self.label_09, 15, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_parameters, 1, 0, 2, 1)
        self.milling_title_label = QtWidgets.QLabel(self.frame_main)
        self.milling_title_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.milling_title_label.setFont(font)
        self.milling_title_label.setTextFormat(QtCore.Qt.PlainText)
        self.milling_title_label.setObjectName("milling_title_label")
        self.gridLayout_2.addWidget(self.milling_title_label, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1037, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_05.setText(_translate("MainWindow", "Label 5"))
        self.pushButton_runMilling.setText(_translate("MainWindow", "Run Milling"))
        self.label_07.setText(_translate("MainWindow", "Label 7"))
        self.label_02.setText(_translate("MainWindow", "Label 2"))
        self.label_06.setText(_translate("MainWindow", "Label 6"))
        self.label_08.setText(_translate("MainWindow", "Label 8"))
        self.label_03.setText(_translate("MainWindow", "Label 3"))
        self.label_01.setText(_translate("MainWindow", "Label 1"))
        self.label_04.setText(_translate("MainWindow", "Label 4"))
        self.label_header.setText(_translate("MainWindow", "Pattern Parameters"))
        self.label_09.setText(_translate("MainWindow", "Label 9"))
        self.milling_title_label.setText(_translate("MainWindow", "AutoLiftout Milling"))

