ip_address: 10.0.0.1
application_file: "autolamella"
plasma_gas: "Argon" # proper case, e.g. Argon, Oxygen
high_voltage: 30000 # volts
stage_rotation_flat_to_electron: 50 # degrees
stage_rotation_flat_to_ion: 230 # degrees
pretilt_angle: 27 # degrees (flat to electron tilt)
stage_tilt_flat_to_ion: 52 # degrees
stage_tilt_landing: 13 # degrees
piescope_enabled: False
high_throughput: False
autolamella: False
initial_position:
  sample_grid: # need to check the coordinate systems
    x: -3.2375e-3
    y: 3.9354e-3
    z: 30.95e-3
    coordinate_system: "Raw"
  landing_grid:
    # x is +6 mm from sample grid center
    x: 2.76265e-3 # x: 2.76265e-3
    # y is the same as sample grid center
    y: 3.9354e-3 # y: 3.9354e-3
    # z is the same as sample grid center
    z: 31.379e-3 # z: 31.379e-3
    coordinate_system: "Raw"